### PR TITLE
1/login signup and user model

### PR DESCRIPTION
**Pull request by jideokus**
Please fill out this template, ignore or delete the parts that are
not relevant to your code.

# Solves issue Number: #1 

## Description
Created user model and added in login and sign up buttons
Added middleware to check authentication and user role
Added user resource controller to handle sign up and login

## Todos
The following things are missing for feature completeness:

- Tests scripts for the user profile
- Create user profile
- Add more fields to user model based on future requirements

## Deploy Notes
- User Model created with first_name,last_name,role,email,password
- Passport has been added and the logged in user model can always be accessed from each request using req.user
- User model has a function isAdmin which checked if the user has an admin or super admin role
- Middlewares have been added to implement the following:
-- loggedInOnly: Forces the user to be logged in to access the route, redirects the user to login page
-- notLoggedInOnly: Redirects the user to the home page if the user is logged in
-- adminsOnly: Redirects the user to the home page if the user is an admin or super admin
-- notAdminOnly: Redirects the user to the home page if the user is not an admin or superadmin

We added the following packages or dependencies:
- "method-override": "~1.0.0",
- "express-session": "~1.0.0",
- "passport" : "~0.1.17",
- "passport-local" : "~0.1.6",
- "passport-facebook" : "~1.0.2",
- "passport-twitter" : "~1.0.2",
- "passport-google-oauth" : "~0.1.5",
- "connect-flash" : "~0.1.1",
- "bcrypt-nodejs" : "latest"
## Steps to Test or Reproduce
- Go to /login
- Go to /signup
## Impacted Areas in Application
The following features or routes might be affected
- The layout has been updated with signup,login and logout links

### CODE REVIEW

**Comment by dvidsilva** [comment]
@jideokus Amazing work, thanks so much. So far it looks good to me, gonna double check in the morning and fix the conflicts, then merge. Thanks!

**Comment by jideokus** [comment]
Sure let me know if I should go ahead to resolve the conflicts

**Comment by dvidsilva** [comment]
Hi, thanks yes, @jideokus if you can solve the conflicts we can make the review faster and approve. thanks!

**Comment by jideokus** [comment]
Sorry just seeing this. Will resolve them now.

**Comment by jideokus** [comment]
Conflicts resolved @dvidsilva. Good to go

**Comment by dvidsilva** [comment]
@jideokus looks like there was a typo on pacakge.json, must have been uncaught on the merge coz it had no conflict. And a couple linting things, fixing that and merging. Thanks :D

**Review by dvidsilva — APPROVED** [review]

**Pull request merged**
